[package]
name = "zkfmi-zk"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
curve25519-dalek.workspace = true
bulletproofs.workspace = true
merlin.workspace = true
sha2.workspace = true
rand_core.workspace = true
subtle.workspace = true

[dev-dependencies]
rand = "0.8"
