[package]
name = "qomm-transport"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "qomm_transport"

[dependencies]
zkfmi-crypto = { workspace = true, features = ["tls"] }
hkdf = "0.12"
zeroize = "1.8"
qomm-proofs.workspace = true
qomm-dsl.workspace = true
qomm-mpc.workspace = true
qomm-zk.workspace = true
qomm-zkpi.workspace = true
qomm-audit.workspace = true
curve25519-dalek.workspace = true
ed25519-dalek.workspace = true
sha2.workspace = true
rand_core.workspace = true
serde.workspace = true
serde_json.workspace = true
base64.workspace = true
hex.workspace = true
thiserror.workspace = true
rand.workspace = true
openssl.workspace = true
libc.workspace = true
merlin.workspace = true

[dev-dependencies]
zkfmi-crypto = { workspace = true, features = ["test-support"] }
tempfile = "3"
merlin.workspace = true
