[package]
name = "qomm-audit"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "qomm_audit"

[dependencies]
zkfmi-crypto.workspace = true
qomm-proofs.workspace = true
qomm-zk.workspace = true
ed25519-dalek.workspace = true
sha2.workspace = true
serde.workspace = true
serde_json.workspace = true
rand_core.workspace = true
thiserror.workspace = true
hex.workspace = true
libc.workspace = true
rand.workspace = true

[dev-dependencies]
rand.workspace = true
curve25519-dalek.workspace = true
tempfile = "3"
